"""Shadow **left** hand info — derived from ``rh_info`` by mirroring.

Asset: ``asset/dextrous_hand/shadow/left_hand_w_fore_arm_touch_contact.xml``
(generated by ``scripts/asset_tools/mirror_lh_xml.py shadow`` — uniform Y-mirror
of our right XML: joints about X/Z have their *axis* negated, ranges kept →
``QPOS_MIRROR_SIGN`` all +1; meshes reflected via the default class
``scale="0.001 -0.001 0.001"``). NOTE: joint-sign convention differs from
Menagerie ``left_hand.xml`` — map when deploying to a real left Shadow hand.

Name rules (right → left), applied in order::

    shadow_rh:    → shadow_lh:     (mocap)
    shadow_rh_    → shadow_lh_     (bodies / touch sites / sensors)
    shadow_r_arm  → shadow_l_arm   (forearm)
    rh_a_         → lh_a_          (taxonomy specific_ctrl_names, actuators rh_A_*)

Attribute names stay ``rh_*`` on purpose (read generically by the codebase).
"""
from grit.util.hand_info import mirror as _mirror
from grit.util.hand_info.shadow import rh_info as _rh

NAME_SUBS = (
    ("shadow_rh:", "shadow_lh:"),
    ("shadow_rh_", "shadow_lh_"),
    ("shadow_r_arm", "shadow_l_arm"),
    ("rh_a_", "lh_a_"),
)
MIRROR_AXIS = 1   # Y
QPOS_MIRROR_SIGN = [1] * 22   # axes flipped in the XML → same qpos = mirrored pose

_ns = _mirror.mirror_info(_rh, NAME_SUBS, mirror_axis=MIRROR_AXIS)
globals().update({k: v for k, v in vars(_ns).items()})
del _ns, _mirror, _rh   # keep only data attributes (HandUtils copies dir())
