"""Inspire **left** hand info — derived from ``rh_info`` by mirroring.

Asset: ``asset/dextrous_hand/inspire/inspire_lh_w_fore_arm_touch_contact_kp60kv334.xml``
(generated by ``scripts/asset_tools/mirror_lh_xml.py inspire`` — Y-mirror of the
right XML; no vendor left asset exists, so joints about X/Z have their *axis*
negated with ranges kept → ``QPOS_MIRROR_SIGN`` all +1, and the right meshes are
reused with ``scale="1 -1 1"``).

Name rules (right → left), applied in order::

    inspire_rh:      → inspire_lh:      (mocap)
    inspire_rh_      → inspire_lh_      (free joint / touch sites / sensors)
    inspire_right_   → inspire_left_    (bodies)
    inspire_r_arm    → inspire_l_arm    (forearm)
    right_           → left_            (taxonomy specific_finger_names: right_thumb …)

Attribute names stay ``rh_*`` on purpose (read generically by the codebase).
"""
from grit.util.hand_info import mirror as _mirror
from grit.util.hand_info.inspire import rh_info as _rh

NAME_SUBS = (
    ("inspire_rh:", "inspire_lh:"),
    ("inspire_rh_", "inspire_lh_"),
    ("inspire_right_", "inspire_left_"),
    ("inspire_r_arm", "inspire_l_arm"),
    ("right_", "left_"),
)
MIRROR_AXIS = 1   # Y
QPOS_MIRROR_SIGN = [1] * 12   # axes flipped in the XML → same qpos = mirrored pose

_ns = _mirror.mirror_info(_rh, NAME_SUBS, mirror_axis=MIRROR_AXIS)
globals().update({k: v for k, v in vars(_ns).items()})
del _ns, _mirror, _rh   # keep only data attributes (HandUtils copies dir())
