"""Tesollo DG-5F **left** hand info — derived from ``rh_info`` by mirroring.

Asset: ``asset/dextrous_hand/tesollo/tesollo_5g_lh_w_fore_arm_touch_contact.xml``
(generated by ``scripts/asset_tools/mirror_lh_xml.py tesollo`` — Y-mirror of
the right XML, same joint axes, X/Z-axis joint ranges reflected, like
``urdf/dg5f_left.urdf``).

Name rules (right → left), applied in order::

    tesollo_rh:   → tesollo_lh:      (mocap)
    tesollo_rh_   → tesollo_lh_      (palm body / sensors)
    tesollo_r_arm → tesollo_l_arm    (forearm)
    rl_dg         → ll_dg            (link bodies, meshes)
    rh_dg         → lh_dg            (joints / actuators / touch sites)

Attribute names stay ``rh_*`` on purpose (read generically by the codebase).
"""
from grit.util.hand_info import mirror as _mirror
from grit.util.hand_info.tesollo import rh_info as _rh

NAME_SUBS = (
    ("tesollo_rh:", "tesollo_lh:"),
    ("tesollo_rh_", "tesollo_lh_"),
    ("tesollo_r_arm", "tesollo_l_arm"),
    ("rl_dg", "ll_dg"),
    ("rh_dg", "lh_dg"),
)
MIRROR_AXIS = 1   # Y

# Joint-sign convention of the mirrored asset: joints about X or Z flip
# (their ranges are reflected, e.g. 1_2 R[-2.54,0] → L[0,2.54]); joints
# about Y (finger flexion) keep sign. Order = qpos order (thumb 1_1..1_4,
# index 2_1..2_4, middle, ring, little 5_1..5_4).
QPOS_MIRROR_SIGN = [-1, -1, -1, -1,   # thumb  1_1(x) 1_2(z) 1_3(x) 1_4(x)
                    -1,  1,  1,  1,   # index  2_1(x) 2_2(y) 2_3(y) 2_4(y)
                    -1,  1,  1,  1,   # middle
                    -1,  1,  1,  1,   # ring
                    -1, -1,  1,  1]   # little 5_1(z) 5_2(x) 5_3(y) 5_4(y)

_ns = _mirror.mirror_info(_rh, NAME_SUBS, mirror_axis=MIRROR_AXIS)
globals().update({k: v for k, v in vars(_ns).items()})
del _ns, _mirror, _rh   # keep only data attributes (HandUtils copies dir())
