"""Wonik Allegro **left** hand info — derived from ``rh_info`` by mirroring.

Asset: ``asset/dextrous_hand/wonik_allegro/allegro_lh_w_fore_arm_touch_contact.xml``
(generated by ``scripts/asset_tools/mirror_lh_xml.py allegro`` — Y-mirror of the
right XML following MuJoCo-Menagerie ``left_hand.xml``: ranges unchanged, the two
thumb joint axes flipped, finger base axes kept, ``base_link_left`` / ``link_12.0_left``).

Name rules (right → left), applied in order::

    alle_r_hand:  → alle_l_hand:     (mocap)
    alle_rh_      → alle_lh_         (free joint / mocap site)
    alle_r_       → alle_l_          (palm / finger bodies / forearm body)
    allegro_rh_   → allegro_lh_      (touch sites / sensors)
    allegro_r_arm → allegro_l_arm    (forearm sensor)
    rh_ff/mf/rf/th → lh_*            (joints / actuators)
    r_palm, r_ff, r_mf, r_rf, r_th → l_*   (taxonomy specific_finger_names)

Attribute names stay ``rh_*`` on purpose (read generically by the codebase).
"""
from grit.util.hand_info import mirror as _mirror
from grit.util.hand_info.allegro import rh_info as _rh

NAME_SUBS = (
    ("alle_r_hand:", "alle_l_hand:"),
    ("alle_rh_", "alle_lh_"),
    ("alle_r_", "alle_l_"),
    ("allegro_rh_", "allegro_lh_"),
    ("allegro_r_arm", "allegro_l_arm"),
    ("rh_ff", "lh_ff"), ("rh_mf", "lh_mf"), ("rh_rf", "lh_rf"), ("rh_th", "lh_th"),
    ("r_palm", "l_palm"), ("r_ff", "l_ff"), ("r_mf", "l_mf"), ("r_rf", "l_rf"), ("r_th", "l_th"),
)
MIRROR_AXIS = 1   # Y

# Joint-sign convention of the Menagerie-style left asset: finger base
# (abduction, axis z kept) flips sign; finger flexion (axis y) keeps; the thumb
# keeps sign on all four joints because its two mirrored axes are flipped in
# the XML itself. Order = qpos order (ff 0..3, mf, rf, th).
QPOS_MIRROR_SIGN = [-1, 1, 1, 1,    # ff  j0(z) j1 j2 j3
                    -1, 1, 1, 1,    # mf
                    -1, 1, 1, 1,    # rf
                     1, 1, 1, 1]    # th  (axes flipped in XML)

_ns = _mirror.mirror_info(_rh, NAME_SUBS, mirror_axis=MIRROR_AXIS)
globals().update({k: v for k, v in vars(_ns).items()})
del _ns, _mirror, _rh   # keep only data attributes (HandUtils copies dir())
